server:
  port: 8083
  servlet:
    context-path: /api/v1

spring:
  application:
    name: ${SERVICE_NAME:ahamo-dummy-demo2-application-service}
  
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:application_service_db}
    username: ${DB_USERNAME:ahamo_user}
    password: ${DB_PASSWORD:ahamo_password}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
        
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

# JWT Configuration (Optional - uncomment if needed)
# jwt:
#   secret: ${JWT_SECRET:mySecretKey}
#   access-token-expiration: 3600000  # 1 hour in milliseconds
#   refresh-token-expiration: 86400000 # 24 hours in milliseconds

# Rate Limiting Configuration (Optional - uncomment if needed)
# rate-limit:
#   login-attempts: 5
#   lockout-duration: 300000 # 5 minutes in milliseconds

# Logging Configuration
logging:
  level:
    com.ahamo.dummy.demo2: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
